version: "3.9"

services:
  strapi:
    build: ./backend
    platform: linux/arm64/v8
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    depends_on:
      - db
    ports:
      - "1337:1337"

  nextjs:
    build: ./frontend
    platform: linux/arm64/v8
    ports:
      - "3000:3000"

  db:
    image: mariadb:10.6
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: linuxserver/phpmyadmin
    platform: linux/arm64/v8
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  db-data:
